db0/pythorhead

- pythorhead/auth.py
Attribution is required per CC BY-SA 3.0
> Add SO attribution

- pyproject.toml
- pythorhead/auth.py
- pythorhead/lemmy.py
- pythorhead/post.py
> python 3.8 compatible static typing

- examples/user.py
- pythorhead/auth.py
- pythorhead/comment.py
- pythorhead/lemmy.py
- pythorhead/post.py
- pythorhead/private_message.py
- pythorhead/site.py
- pythorhead/user.py
> feat: Allow multiple lemmy instances logged in to different sites

- examples/pm.py
- examples/user.py
- pythorhead/auth.py
- pythorhead/comment.py
- pythorhead/image.py
- pythorhead/lemmy.py
- pythorhead/post.py
- pythorhead/private_message.py
- pythorhead/requestor.py
- pythorhead/site.py
- pythorhead/user.py
Implementation for #18
Note: I format my code with `black` maybe we should be formatting the code in the same way to minimize code changes by the formatter.
> initial image upload implentation

- examples/site.py
- pythorhead/requestor.py
Sites like beehaw.org are very particular
> feat: Request Headers

- pythorhead/community.py
- pythorhead/lemmy.py
Add endpoint for creating a community
> feat: community create

- examples/pic.py
- pythorhead/community.py
> fix create community

- pythorhead/community.py
I've added a function to the community class which allows for subscribing and unsubscribing from the current account.
Let me know if you even want this functionality or whether I need to change anything for it to be merged.
> added function for subscribing and unsubscribing

- examples/pic.py
- pythorhead/comment.py
- pythorhead/community.py
- pythorhead/post.py
- pythorhead/user.py
> Purge for Communities, Comments, Posts and Users

- pythorhead/private_message.py
provided by: @Demigodrick
closes #45
> feat: marks PM as read

- pythorhead/community.py
Added add mod to community function
> Add "Add mod to community"

- pythorhead/lemmy.py
> Implemented search

- pythorhead/admin.py
- pythorhead/lemmy.py
Adds a specific admin class (hope thats ok) and the function to pull list of applications.
> Add admin class & list applications admin function

- pythorhead/community.py
- pythorhead/types/listing.py
- pythorhead/types/sort.py
> Fix community.list

- pythorhead/comment.py
Fixes https://github.com/db0/pythorhead/issues/59
> Fix community list by type

- pythorhead/comment.py
+function to distinguish a comment as a mod comment
\- distinguished argument for the edit comment function as it does nothing
> Functionallity to distinguish comments.

- README.md
- examples/community.py
- pythorhead/lemmy.py
- pythorhead/requestor.py
- pythorhead/types/__init__.py
- pythorhead/types/search.py
When using discover_community, if the community is now known, the system will initiate a search for it. 
Closes #68
> Feat: Community discovery also does a search

- pythorhead/comment.py
> feat: comment get

- pyproject.toml
- pythorhead/__init__.py
- pythorhead/requestor.py
> feat: Support for 0.19 auth

- pythorhead/community.py
Added option to ban someone from a community instead of only allowing for sidewide ban.
This is my first ever pull request to a public repo like this, so sorry if I screwed anything up.
> added ban_from_community

- pythorhead/user.py
> (issue #93) fix: saved_only works for users now

- pyproject.toml
tested and works with python 3.12.4
> support python 3.12

- examples/user_class.py
- pyproject.toml
- pythorhead/classes/user.py
- pythorhead/lemmy.py
- pythorhead/user.py
- pythorhead/utils.py
Requires python 3.10+ from now on
> feat: adds object classes

- examples/modlog.py
- pythorhead/lemmy.py
- pythorhead/modlog.py
- pythorhead/types/__init__.py
- pythorhead/types/modlog.py
This adds the GetModlog API function.
See https://join-lemmy.org/api/interfaces/GetModlog.html
> Add GetModlog functionality

- pythorhead/admin.py
The added function allows for the acception or rejection of a user application. An admin user is required for this to work.
> Acception and rejection of user applications

- pythorhead/admin.py
- pythorhead/classes/admin.py
fix: process_application uses application_id as key name now
> feat: aprove/deny application requests from class
